/**
 * Asset consistency: every require()'d sprite/sound in the emoji and sound
 * registries must exist on disk (they're generated by scripts/gen-*.mjs — a
 * missing run would otherwise only surface as a red screen at bundle time).
 * Parsed from source so this Node suite never imports binary assets.
 */

import { describe, it, expect } from "vitest";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const SRC = join(__dirname, "..", "src");

function requiredAssets(file: string): string[] {
  const source = readFileSync(join(SRC, file), "utf8");
  return [...source.matchAll(/require\("\.\.\/\.\.\/(assets\/[^"]+)"\)/g)].map((m) => m[1]!);
}

/** Every .ts/.tsx under src/, recursively. */
function sourceFiles(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) return sourceFiles(full);
    return /\.tsx?$/.test(entry) ? [full] : [];
  });
}

describe("generated assets", () => {
  // The two checks below name the specific registries and the script that
  // rebuilds them. This one is the net for everything else — a new module that
  // require()s an asset, or a file moved without its references.
  it("has every asset require()'d anywhere in src/", () => {
    const broken: string[] = [];
    for (const file of sourceFiles(SRC)) {
      const text = readFileSync(file, "utf8");
      for (const m of text.matchAll(/require\(\s*"([^"]*assets\/[^"]+)"\s*\)/g)) {
        const target = join(file, "..", m[1]!);
        if (!existsSync(target)) broken.push(`${file.slice(SRC.length + 1)} -> ${m[1]}`);
      }
    }
    expect(broken).toEqual([]);
  });

  // Expo reads these at build time, so a stale path is not a type error and not
  // a bundle error — it is a missing or wrong icon in a store build.
  it("has every asset app.json points at", () => {
    const app = JSON.parse(readFileSync(join(__dirname, "..", "app.json"), "utf8")).expo;
    const paths: string[] = [
      app.icon,
      app.web?.favicon,
      app.android?.adaptiveIcon?.foregroundImage,
      app.android?.adaptiveIcon?.backgroundImage,
      app.android?.adaptiveIcon?.monochromeImage,
    ].filter(Boolean);
    expect(paths.length).toBe(5);
    expect(paths.filter((p) => !existsSync(join(__dirname, "..", p)))).toEqual([]);
  });

  it("has every sprite/sound referenced by the emoji registry", () => {
    const paths = requiredAssets("lib/emoji.ts");
    expect(paths.length).toBeGreaterThanOrEqual(8);
    for (const p of paths) {
      expect(existsSync(join(__dirname, "..", p)), `missing ${p} — run scripts/gen-emoji.mjs`).toBe(true);
    }
  });

  it("gives every reaction emoji a sound the sound layer actually defines", () => {
    // resolveEmoji()'s consumers fall back to "pop" on a miss, so a typo'd or
    // stale sound name degrades silently to a UI click instead of failing —
    // exactly how thumbs/gg went unnoticed while borrowing pop/finish.
    const declared = new Set(
      [...readFileSync(join(SRC, "lib/sound.ts"), "utf8").matchAll(/^\s{2}(\w+): \{ source:/gm)].map(
        (m) => m[1]!,
      ),
    );
    expect(declared.size).toBeGreaterThanOrEqual(19);

    const used = [
      ...readFileSync(join(SRC, "lib/emoji.ts"), "utf8").matchAll(/sound: "(\w+)"/g),
    ].map((m) => m[1]!);
    expect(used.length).toBeGreaterThanOrEqual(8);

    for (const name of used) {
      expect(declared.has(name), `emoji.ts uses sound "${name}", absent from sound.ts SPECS`).toBe(
        true,
      );
    }
  });

  it("keeps each reaction voice distinct, so none borrows a UI sound", () => {
    const source = readFileSync(join(SRC, "lib/emoji.ts"), "utf8");
    const sounds = [...source.matchAll(/sound: "(\w+)"/g)].map((m) => m[1]!);
    expect(new Set(sounds).size, "two emoji share one sound").toBe(sounds.length);
    for (const generic of ["pop", "finish", "ding", "tap", "msg"]) {
      expect(sounds, `a reaction is reusing the generic "${generic}" UI sound`).not.toContain(
        generic,
      );
    }
  });

  it("has every wav referenced by the sound layer", () => {
    const paths = requiredAssets("lib/sound.ts");
    expect(paths.length).toBeGreaterThanOrEqual(17);
    for (const p of paths) {
      expect(
        existsSync(join(__dirname, "..", p)),
        `missing ${p} — run scripts/gen-sfx.mjs / process-reaction-sfx.mjs`,
      ).toBe(true);
    }
  });
});
