/**
 * Asset consistency: every require()'d sprite/sound in the emoji and sound
 * registries must exist on disk (they're generated by scripts/gen-*.mjs — a
 * missing run would otherwise only surface as a red screen at bundle time).
 * Parsed from source so this Node suite never imports binary assets.
 */

import { describe, it, expect } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const SRC = join(__dirname, "..", "src");

function requiredAssets(file: string): string[] {
  const source = readFileSync(join(SRC, file), "utf8");
  return [...source.matchAll(/require\("\.\.\/\.\.\/(assets\/[^"]+)"\)/g)].map((m) => m[1]!);
}

describe("generated assets", () => {
  it("has every sprite/sound referenced by the emoji registry", () => {
    const paths = requiredAssets("lib/emoji.ts");
    expect(paths.length).toBeGreaterThanOrEqual(8);
    for (const p of paths) {
      expect(existsSync(join(__dirname, "..", p)), `missing ${p} — run scripts/gen-emoji.mjs`).toBe(true);
    }
  });

  it("gives every reaction emoji a sound the sound layer actually defines", () => {
    // resolveEmoji()'s consumers fall back to "pop" on a miss, so a typo'd or
    // stale sound name degrades silently to a UI click instead of failing —
    // exactly how thumbs/gg went unnoticed while borrowing pop/finish.
    const declared = new Set(
      [...readFileSync(join(SRC, "lib/sound.ts"), "utf8").matchAll(/^\s{2}(\w+): \{ source:/gm)].map(
        (m) => m[1]!,
      ),
    );
    expect(declared.size).toBeGreaterThanOrEqual(19);

    const used = [
      ...readFileSync(join(SRC, "lib/emoji.ts"), "utf8").matchAll(/sound: "(\w+)"/g),
    ].map((m) => m[1]!);
    expect(used.length).toBeGreaterThanOrEqual(8);

    for (const name of used) {
      expect(declared.has(name), `emoji.ts uses sound "${name}", absent from sound.ts SPECS`).toBe(
        true,
      );
    }
  });

  it("keeps each reaction voice distinct, so none borrows a UI sound", () => {
    const source = readFileSync(join(SRC, "lib/emoji.ts"), "utf8");
    const sounds = [...source.matchAll(/sound: "(\w+)"/g)].map((m) => m[1]!);
    expect(new Set(sounds).size, "two emoji share one sound").toBe(sounds.length);
    for (const generic of ["pop", "finish", "ding", "tap", "msg"]) {
      expect(sounds, `a reaction is reusing the generic "${generic}" UI sound`).not.toContain(
        generic,
      );
    }
  });

  it("has every wav referenced by the sound layer", () => {
    const paths = requiredAssets("lib/sound.ts");
    expect(paths.length).toBeGreaterThanOrEqual(17);
    for (const p of paths) {
      expect(
        existsSync(join(__dirname, "..", p)),
        `missing ${p} — run scripts/gen-sfx.mjs / process-reaction-sfx.mjs`,
      ).toBe(true);
    }
  });
});
