/**
 * Asset consistency: every require()'d sprite/sound in the emoji and sound
 * registries must exist on disk (they're generated by scripts/gen-*.mjs — a
 * missing run would otherwise only surface as a red screen at bundle time).
 * Parsed from source so this Node suite never imports binary assets.
 */

import { describe, it, expect } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const SRC = join(__dirname, "..", "src");

function requiredAssets(file: string): string[] {
  const source = readFileSync(join(SRC, file), "utf8");
  return [...source.matchAll(/require\("\.\.\/\.\.\/(assets\/[^"]+)"\)/g)].map((m) => m[1]!);
}

describe("generated assets", () => {
  it("has every sprite/sound referenced by the emoji registry", () => {
    const paths = requiredAssets("lib/emoji.ts");
    expect(paths.length).toBeGreaterThanOrEqual(8);
    for (const p of paths) {
      expect(existsSync(join(__dirname, "..", p)), `missing ${p} — run scripts/gen-emoji.mjs`).toBe(true);
    }
  });

  it("has every wav referenced by the sound layer", () => {
    const paths = requiredAssets("lib/sound.ts");
    expect(paths.length).toBeGreaterThanOrEqual(17);
    for (const p of paths) {
      expect(
        existsSync(join(__dirname, "..", p)),
        `missing ${p} — run scripts/gen-sfx.mjs / gen-reaction-sfx.mjs`,
      ).toBe(true);
    }
  });
});
